### ISSUE TITLE
genius no longer returns lyrics

### ISSUE THREAD

**Issue by redapemusic35** [JosiahParry/genius#60] opened 2021-07-08 00:26 UTC
I will first say that I absolutely love this script. However, it has now stopped returning the lyrics using: `emotions_math <- genius_album(artist = "Margaret Glaspy", album = "Emotions and Math")` and `emotions_math`, returns: 
![image](https://user-images.githubusercontent.com/23493710/124844252-671d7800-df59-11eb-912c-6c3beb0262a0.png)

New:

Also, doing this: 
```
artist_albums <- tribble(
 ~artist, ~album,
 "J. Cole", "KOD",
 "Sampha", "Process"
)


artist_albums %>%
 add_genius(artist, album)
```
gets this:

![image](https://user-images.githubusercontent.com/23493710/125150593-8efe0e80-e106-11eb-9797-bd9fc3e526c8.png)

Pdf output looks like this:

![image](https://user-images.githubusercontent.com/23493710/125150639-fe73fe00-e106-11eb-8f2a-038f160e5d3a.png)

**Comment by JosiahParry** [comment] 2021-07-24 15:46
Duplicate of https://github.com/JosiahParry/genius/issues/58

**Closed by JosiahParry** 2021-07-24 15:46 UTC
